### ISSUE TITLE
Extract WebTty.Exec into a separate library published on nuget

### ISSUE THREAD

**Issue by nickvdyck** [nickvdyck/webtty#142]
`WebTty.Exec` has organically grown out of `webtty` into what it is now.  And I think this is the point where I can extract it into a separate library and package so that I can start using it in other projects. 

Having this in a separate repository will also allow me to simplify the `webtty` build process and remove some hacks I put in place to make it all work.

**To-Do**
- [x] Find a name for this library. I would prefer to publish it under a different name because WebTty gives it the connotation that it's only useful for web projects.
- [x] Move WebTty.Exec into new library
- [x] Publish to nuget.
- [x] Consume new package and remove `WebTty.Exec`

**Comment by nickvdyck** [comment]
- Moved `WebTty.Exec` into `BtrExec` (Better Exec): https://github.com/nickvdyck/BtrExec
- Removed `WebTty.Exec` and started using `BtrExec` as of this commit: https://github.com/nickvdyck/webtty/commit/1ae14b63ed941cb37759e5b9989385d5ab852131

**Comment by nickvdyck** [comment]
@FeodorFitsner Not sure if you still have a need for a process library that can fork pty's. But if you are still interested I extracted this functionality out of this project and into [BtrExec](https://github.com/nickvdyck/BtrExec).

**Comment by FeodorFitsner** [comment]
Thank you! Will look into that.
